In [1]:
import torch 

In [2]:
a = torch.tensor([2,2,1])
b = torch.tensor([[1,2,3],[3,4,5],[5,6,7]])
a,b

(tensor([2, 2, 1]),
 tensor([[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]))

In [4]:
a.shape,b.shape,b.shape[0],a.size(),b.size()

(torch.Size([3]), torch.Size([3, 3]), 3, torch.Size([3]), torch.Size([3, 3]))

In [5]:
#float tensor 
c = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
print(c)
print(c.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.float32


In [6]:
c.mean(),c.std()

(tensor(5.), tensor(2.7386))

In [20]:
b.view(-1,1)


tensor([[1],
        [2],
        [3],
        [3],
        [4],
        [5],
        [5],
        [6],
        [7]])

In [19]:
b.view(3,3)

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

In [21]:
three_dim = torch.randn(2,3,4)
#2channel,3 rows,4 columns only for torch whereas others has row,col,channel
three_dim

tensor([[[ 0.2812,  0.1941,  0.2883,  0.4131],
         [-0.9726, -2.3843, -0.5137,  0.9716],
         [-0.3206, -1.8828, -1.1457,  0.1835]],

        [[ 1.0635,  0.3991,  0.3137,  1.7783],
         [ 0.9797, -1.3750, -1.9096, -0.1615],
         [-1.2439,  1.6500,  1.8888,  0.1404]]])

In [22]:
three_dim.view(2,12)

tensor([[ 0.2812,  0.1941,  0.2883,  0.4131, -0.9726, -2.3843, -0.5137,  0.9716,
         -0.3206, -1.8828, -1.1457,  0.1835],
        [ 1.0635,  0.3991,  0.3137,  1.7783,  0.9797, -1.3750, -1.9096, -0.1615,
         -1.2439,  1.6500,  1.8888,  0.1404]])

In [23]:
#create a array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint(6,10,(3,3))
print(in_array)
print(in_array.dtype)

tensor([[7, 7, 7],
        [9, 9, 9],
        [7, 6, 7]])
torch.int64


In [24]:
torch.numel(in_array)

9

In [30]:
z = torch.zeros(3,3,dtype=torch.long)
print(z)
o = torch.ones(3,3)
print(o)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [31]:
r2_like = torch.randn_like(o)
r2_like

tensor([[ 0.3887, -0.5369,  0.9423],
        [ 0.3496, -1.1445, -1.0498],
        [-0.2790, -0.6836, -0.0397]])

In [32]:
o.add_(r2_like)

tensor([[ 1.3887,  0.4631,  1.9423],
        [ 1.3496, -0.1445, -0.0498],
        [ 0.7210,  0.3164,  0.9603]])

# AutoGrad

In [36]:
x = torch.tensor([1.,2.,3.],requires_grad=True)
y = torch.tensor([4.,5.,6.],requires_grad=True)

In [37]:
z = x+y
print(z.grad_fn)

In [39]:
s = z.sum()
s.grad_fn

In [40]:
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [44]:
x = torch.randn(2,2,requires_grad=True)
y = torch.randn(2,2)
print(y.requires_grad)

False


In [45]:
y.requires_grad_()

tensor([[ 0.8917, -0.9346],
        [ 0.0900, -1.2552]], requires_grad=True)

In [46]:
z = x+y
z.grad_fn,z.requires_grad

(<AddBackward0 at 0x1555d6bda20>, True)

In [48]:
new_z=z.detach()

In [51]:
x.requires_grad,(x+10).requires_grad

(True, True)

In [52]:
with torch.no_grad():
    print((x+10).requires_grad)

False


In [53]:
import torch 
from torch import nn

In [56]:
prediction = torch.randn(4,5)
label = torch.randn(4,5)
mse = nn.MSELoss(reduction='mean')
loss = mse(prediction,label)
loss

tensor(1.9806)

In [58]:
label = torch.zeros(4,5).random_(0,2)
label

tensor([[0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0.],
        [1., 0., 1., 1., 1.],
        [0., 1., 0., 1., 1.]])

In [59]:
sigmoid = nn.Sigmoid()
bce = nn.BCELoss(reduction='mean')
bce(sigmoid(prediction),label)

tensor(0.7927)

In [60]:
bces = nn.BCEWithLogitsLoss(reduction='mean')
bces(prediction,label)

tensor(0.7927)

# Weight Initialization

In [61]:
layer = nn.Linear(5,5)
layer

Linear(in_features=5, out_features=5, bias=True)

In [67]:
nn.init.constant_(layer.weight,val=0)

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)

In [69]:
nn.init.normal_(layer.bias,mean=0,std=1)

Parameter containing:
tensor([ 1.7832,  0.5823, -1.5057, -1.8180, -0.0413], requires_grad=True)